version: "2.2"
services:
  prometheus:
    build:
      context: ./prometheus
    links:
      - app1
      - app2
      - app3
    ports:
      - 9090:9090
    command: >
      --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus
      --web.console.libraries=/usr/share/prometheus/console_libraries
      --web.console.templates=/usr/share/prometheus/consoles
      --web.enable-lifecycle
  app1:
    build:
      context: ./app
    cap_add:
      - NET_ADMIN
    working_dir: /app
    volumes:
      - ./app:/app
    depends_on:
      - fakethirdpartysite
    command: watcher -addr=:8080
  app2:
    build:
      context: ./app
    cap_add:
      - NET_ADMIN
    working_dir: /app
    volumes:
      - ./app:/app
    depends_on:
      - fakethirdpartysite
    command: watcher -addr=:8080
  app3:
    build:
      context: ./app
    cap_add:
      - NET_ADMIN
    working_dir: /app
    volumes:
      - ./app:/app
    depends_on:
      - fakethirdpartysite
    command: watcher -addr=:8080
  nginx:
    build:
      context: ./nginx
    depends_on:
      - app1
      - app2
      - app3
    ports:
      - 8080:80
  fakethirdpartysite:
    build:
      context: ./fakethirdpartysite
